name: Build and Deploy

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: sh80165/text-to-sql
  MANIFEST_REPO: lsh9672/text-to-sql-manifest
  MANIFEST_FILE_PATH: langchain/app/deployment.yml

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set build date
      run: echo "BUILD_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

    - name: Set short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_DATE }}_${{ env.SHORT_SHA }}

  update-deployment:
    needs: build-push
    runs-on: ubuntu-latest
    
    steps:
    - name: Update private deployment repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.MANIFEST_REPO }}  # 실제 private CD 레포 이름으로 변경
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}  # private repo 접근용 PAT
        path: deployment
    
    - name: Update image tag with Kustomize
      run: |
        cd deployment
        
        # sed로 이미지 태그 업데이트
        sed -i "s|sh80165/text-to-sql:.*|sh80165/text-to-sql:${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_DATE }}_${{ env.SHORT_SHA }}|g" ${{ env.MANIFEST_FILE_PATH }}
        
        git config user.name "lsh9672"
        git config user.email "lsh80165@gmail.com"
        git add .
        git commit -m "Feat : Update text-to-sql image to ${{ github.sha }}"
        git push